import { CalendarDays, Info, Search, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { PaymentBreadcrumb } from "../components/PaymentBreadcrumb.jsx";

export function PaymentSearchPage() {
  const now = new Date(); const navigate = useNavigate(); const [year, setYear] = useState(String(now.getFullYear())); const [month, setMonth] = useState(String(now.getMonth() + 1));
  return <><PaymentBreadcrumb items={[{ label: "Lập bảng thanh toán" }]} /><div className="pay-intro"><h2>Chọn kỳ thanh toán</h2><p>Chọn năm và tháng cần lập bảng thanh toán cho doanh nghiệp.</p></div><section className="pay-search-period"><div className="pay-search-fields"><label className="pay-field"><span>Năm thanh toán</span><div className="with-icon"><CalendarDays size={15} /><select value={year} onChange={(event) => setYear(event.target.value)}>{[0,1,2,3].map((offset) => <option key={offset}>{now.getFullYear() - offset}</option>)}</select></div><small>Chọn năm tài chính áp dụng</small></label><label className="pay-field"><span>Tháng thanh toán</span><div className="with-icon"><CalendarDays size={15} /><select value={month} onChange={(event) => setMonth(event.target.value)}>{Array.from({ length: 12 }, (_, index) => <option value={index + 1} key={index}>Tháng {index + 1}</option>)}</select></div><small>Chọn một trong 12 tháng cần lập bảng</small></label><label className="pay-field"><span>Trạng thái kỳ</span><div className="with-icon"><CalendarDays size={15} /><select><option>Tất cả trạng thái</option><option>Đang mở</option><option>Đã đóng</option></select></div><small>Lọc theo tiến độ xử lý hiện tại</small></label></div><div className="pay-search-footer"><button className="pay-text-action"><SlidersHorizontal size={16} />Bộ lọc nâng cao</button><div><button className="pay-button outline">Đặt lại</button><button className="pay-button primary" onClick={() => navigate(`/payments/periods/${year}-${month}/customers`)}><Search size={16} />Tiếp tục</button></div></div></section><section className="pay-tip-grid"><article className="blue"><Info size={20} /><div><strong>Hướng dẫn lập bảng</strong><p>Chọn Năm và Tháng, sau đó tiếp tục để xem các khách hàng đủ điều kiện lập bảng thanh toán trong kỳ.</p></div></article></section><div className="pay-engine-status"><span>System engine status: active</span></div></>;
}
