import { ArrowLeft, Info, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { PaymentBreadcrumb } from "../components/PaymentBreadcrumb.jsx";
import { PaymentLines } from "../components/PaymentLines.jsx";
import { PaymentState } from "../components/PaymentState.jsx";
import { PaymentStatus } from "../components/PaymentStatus.jsx";
import { PaymentTotals } from "../components/PaymentTotals.jsx";
import { useCreateAdjustment, usePayment, useUpdatePayment } from "../hooks/usePayments.js";

export function PaymentEditPage({ adjustment = false }) {
  const { paymentId } = useParams(); const navigate = useNavigate(); const { data: payment, isPending, error } = usePayment(paymentId); const update = useUpdatePayment(); const adjust = useCreateAdjustment(); const [values, setValues] = useState({}); const [reason, setReason] = useState(""); const [revisionId, setRevisionId] = useState("");
  useEffect(() => { if (payment) setValues(Object.fromEntries(payment.lines.map((line) => [line.service_id, line.billing_quantity]))); }, [payment]);
  if (isPending) return <PaymentState title="Đang tải dữ liệu..." />; if (error) return <PaymentState title="Không thể tải dữ liệu" description={error.message} />;
  const expected = adjustment ? "REVISION_REQUESTED" : "DRAFT"; if (payment.status !== expected) return <PaymentState title="Không thể chỉnh sửa" description={`Bảng đang ở trạng thái ${payment.status}.`} />;
  const lines = payment.lines.map((line) => ({ service_id: line.service_id, billing_quantity: Number(values[line.service_id]) })); const mutation = adjustment ? adjust : update;
  const save = (event) => { event.preventDefault(); const payload = adjustment ? { revision_request_id: revisionId, adjustment_note: reason, lines } : { reason, lines }; mutation.mutate({ id: paymentId, payload }, { onSuccess: () => navigate(`/payments/${paymentId}`) }); };
  if (adjustment) return <form onSubmit={save}><Link className="pay-back" to={`/payments/${paymentId}`}><ArrowLeft size={16} />Quay lại danh sách</Link><div className="revision-heading"><div><h2>Điều chỉnh bảng thanh toán - {payment.id}</h2></div><PaymentStatus status={payment.status} /></div><section className="revision-request"><Info /><div><strong>Yêu cầu chỉnh sửa từ người duyệt</strong><div className="request-meta"><p><small>Người yêu cầu</small>Nguyễn Văn B (Nhân viên Pháp chế)</p><p><small>Thời gian</small>Đang cập nhật</p><p><small>Lý do</small>Sản lượng thanh toán chưa thống nhất</p></div><p className="request-detail"><small>Nội dung chi tiết</small>Kiểm tra lại sản lượng dịch vụ. Có sự sai lệch giữa biên bản đối soát và bảng tính tổng hợp.</p></div></section><div className="revision-grid"><section className="pay-panel common-info"><h3>ⓘ Thông tin chung</h3><label>Mã bảng thanh toán<input value={payment.id} readOnly /></label><label>Đối tác<input value={payment.customer_id} readOnly /></label><label>Kỳ thanh toán<input value={`${payment.period_start} – ${payment.period_end}`} readOnly /></label><label>Hợp đồng tham chiếu<input value={payment.contract_id} readOnly /></label></section><section className="pay-panel revision-lines"><h3>▣ Chi tiết bảng thanh toán</h3><PaymentLines lines={payment.lines} editable values={values} onChange={(id, value) => setValues((current) => ({ ...current, [id]: value }))} /></section><section className="pay-panel revision-total"><h3>▤ Tổng hợp thanh toán & Ghi chú</h3><PaymentTotals payment={payment} /><label>Ghi chú giải trình điều chỉnh<textarea required minLength="3" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Nhập lý do hoặc giải trình các thay đổi..." /></label><label>Mã yêu cầu chỉnh sửa<input required value={revisionId} onChange={(event) => setRevisionId(event.target.value)} placeholder="revision-request-id" /></label></section><section className="pay-panel revision-history"><h3>◴ Lịch sử điều chỉnh</h3><div><strong>Yêu cầu chỉnh sửa</strong><p>Người duyệt yêu cầu kiểm tra lại sản lượng.</p></div><div><strong>Trình phê duyệt lần 1</strong><p>Kế toán đã khởi tạo và trình phê duyệt.</p></div><div><strong>Khởi tạo nháp</strong><p>Hệ thống tự động tạo bản nháp.</p></div></section></div>{mutation.error ? <div className="pay-alert error">{mutation.error.message}</div> : null}<div className="pay-bottom-bar"><span>◉ Đang ở chế độ điều chỉnh theo yêu cầu</span><div><Link className="pay-button outline" to={`/payments/${paymentId}`}>Hủy</Link><button className="pay-button primary"><Save size={16} />Lưu thay đổi</button></div></div></form>;
  return <form onSubmit={save}><PaymentBreadcrumb items={[{ label: payment.id, to: `/payments/${payment.id}` }, { label: "Điều chỉnh" }]} /><div className="pay-page-heading"><h1>Điều chỉnh bảng thanh toán</h1><PaymentStatus status={payment.status} /></div><div className="pay-info-banner"><Info size={18} />Bảng thanh toán đang ở trạng thái Nháp và được phép điều chỉnh.</div><div className="draft-edit-grid"><div><section className="pay-panel draft-common"><h3>▤ Thông tin chung</h3><div><p><small>Mã BTT</small><strong>{payment.id}</strong></p><p><small>Khách hàng</small><strong>{payment.customer_id}</strong></p><p><small>Kỳ thanh toán</small><strong>{payment.period_start} – {payment.period_end}</strong></p><p><small>Số Hợp đồng</small><strong>{payment.contract_id}</strong></p></div></section><section className="pay-panel draft-lines"><h3>▣ Chi tiết bảng thanh toán</h3><PaymentLines lines={payment.lines} editable values={values} onChange={(id, value) => setValues((current) => ({ ...current, [id]: value }))} /></section></div><aside><section className="pay-panel draft-summary"><h3>▣ Tổng hợp thanh toán</h3><PaymentTotals payment={payment} /><label>Ghi chú điều chỉnh<textarea required minLength="3" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Nhập lý do điều chỉnh sản lượng hoặc đơn giá..." /></label></section><section className="pay-panel draft-history"><h3>◴ Lịch sử điều chỉnh</h3>{payment.adjustments?.length ? payment.adjustments.map((item) => <div key={item.id}><strong>{item.change_type}</strong><p>{item.adjustment_note}</p></div>) : <div><strong>Hệ thống</strong><p>Khởi tạo bản nháp điều chỉnh đầu tiên.</p></div>}</section></aside></div>{mutation.error ? <div className="pay-alert error">{mutation.error.message}</div> : null}<div className="pay-bottom-bar"><span /><div><Link className="pay-button outline" to={`/payments/${paymentId}`}>Hủy</Link><button className="pay-button primary"><Save size={16} />Lưu thay đổi</button></div></div></form>;
}
