CREATE TABLE IF NOT EXISTS service (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(500) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    unit VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS price_list (
    id VARCHAR(20) PRIMARY KEY,
    description VARCHAR(500) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS price_list_detail (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_list_id VARCHAR(20) NOT NULL REFERENCES price_list(id) ON DELETE CASCADE,
    service_id INTEGER NOT NULL REFERENCES service(id),
    unit_price DECIMAL(18, 2) NOT NULL
);

INSERT INTO service (id, name, description, is_active, unit)
VALUES
    (1, 'Bốc xếp Container 20ft', 'DV001', TRUE, 'Container'),
    (2, 'Bốc xếp Container 40ft', 'DV002', TRUE, 'Container'),
    (3, 'Lưu kho', 'DV003', TRUE, 'Ngày'),
    (4, 'Vận chuyển nội địa', 'DV004', TRUE, 'Chuyến'),
    (5, 'Kiểm đếm hàng hóa', 'DV005', TRUE, 'Lô hàng'),
    (6, 'Nâng hạ Container', 'DV006', TRUE, 'Lần')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('service', 'id'), (SELECT MAX(id) FROM service));

INSERT INTO price_list (
    id,
    description,
    effective_from,
    effective_to,
    status
)
VALUES (
    'BG-2026-001',
    'Bảng giá Version 1',
    DATE '2026-01-01',
    DATE '2026-12-31',
    'EFFECTIVE'
)
ON CONFLICT (id) DO NOTHING;

-- Option 2: only services with effective price rows are contract-usable.
-- DV005 and DV006 remain catalog services, but are unavailable for contracts
-- until an effective price is added for them.
INSERT INTO price_list_detail (price_list_id, service_id, unit_price)
SELECT 'BG-2026-001', 1, 350000.00
WHERE NOT EXISTS (
    SELECT 1
    FROM price_list_detail
    WHERE price_list_id = 'BG-2026-001' AND service_id = 1
);

INSERT INTO price_list_detail (price_list_id, service_id, unit_price)
SELECT 'BG-2026-001', 2, 550000.00
WHERE NOT EXISTS (
    SELECT 1
    FROM price_list_detail
    WHERE price_list_id = 'BG-2026-001' AND service_id = 2
);

INSERT INTO price_list_detail (price_list_id, service_id, unit_price)
SELECT 'BG-2026-001', 3, 120000.00
WHERE NOT EXISTS (
    SELECT 1
    FROM price_list_detail
    WHERE price_list_id = 'BG-2026-001' AND service_id = 3
);

INSERT INTO price_list_detail (price_list_id, service_id, unit_price)
SELECT 'BG-2026-001', 4, 2500000.00
WHERE NOT EXISTS (
    SELECT 1
    FROM price_list_detail
    WHERE price_list_id = 'BG-2026-001' AND service_id = 4
);

SELECT setval(
    pg_get_serial_sequence('price_list_detail', 'id'),
    COALESCE((SELECT MAX(id) FROM price_list_detail), 1)
);
